server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    instance:
      preferIpAddress: true
spring:
  application:
    name: service-registry

service-registry:
  ribbon:
    eureka:
      enabled: true
    listOfServices: localhost:8075, localhost:8524, localhost:8068, localhost:8524